/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.usemoon.MoonSDK.Api;
using com.usemoon.MoonSDK.Model;
using com.usemoon.MoonSDK.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace com.usemoon.MoonSDK.Test.Model
{
    /// <summary>
    ///  Class for testing AbiOutput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AbiOutputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AbiOutput
        //private AbiOutput instance;

        public AbiOutputTests()
        {
            // TODO uncomment below to create an instance of AbiOutput
            //instance = new AbiOutput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AbiOutput
        /// </summary>
        [Test]
        public void AbiOutputInstanceTest()
        {
            // TODO uncomment below to test "IsType" AbiOutput
            //Assert.IsType<AbiOutput>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Components'
        /// </summary>
        [Test]
        public void ComponentsTest()
        {
            // TODO unit test for the property 'Components'
        }
        /// <summary>
        /// Test the property 'InternalType'
        /// </summary>
        [Test]
        public void InternalTypeTest()
        {
            // TODO unit test for the property 'InternalType'
        }
    }
}
