/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.usemoon.MoonSDK.Api;
using com.usemoon.MoonSDK.Model;
using com.usemoon.MoonSDK.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace com.usemoon.MoonSDK.Test.Model
{
    /// <summary>
    ///  Class for testing AccountControllerResponseData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AccountControllerResponseDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AccountControllerResponseData
        //private AccountControllerResponseData instance;

        public AccountControllerResponseDataTests()
        {
            // TODO uncomment below to create an instance of AccountControllerResponseData
            //instance = new AccountControllerResponseData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AccountControllerResponseData
        /// </summary>
        [Test]
        public void AccountControllerResponseDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" AccountControllerResponseData
            //Assert.IsType<AccountControllerResponseData>(instance);
        }

        /// <summary>
        /// Test the property 'Nonce'
        /// </summary>
        [Test]
        public void NonceTest()
        {
            // TODO unit test for the property 'Nonce'
        }
        /// <summary>
        /// Test the property 'Balance'
        /// </summary>
        [Test]
        public void BalanceTest()
        {
            // TODO unit test for the property 'Balance'
        }
        /// <summary>
        /// Test the property 'TransactionHash'
        /// </summary>
        [Test]
        public void TransactionHashTest()
        {
            // TODO unit test for the property 'TransactionHash'
        }
        /// <summary>
        /// Test the property 'SignedTransaction'
        /// </summary>
        [Test]
        public void SignedTransactionTest()
        {
            // TODO unit test for the property 'SignedTransaction'
        }
        /// <summary>
        /// Test the property 'RawTransaction'
        /// </summary>
        [Test]
        public void RawTransactionTest()
        {
            // TODO unit test for the property 'RawTransaction'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'Transactions'
        /// </summary>
        [Test]
        public void TransactionsTest()
        {
            // TODO unit test for the property 'Transactions'
        }
        /// <summary>
        /// Test the property 'MoonScanUrl'
        /// </summary>
        [Test]
        public void MoonScanUrlTest()
        {
            // TODO unit test for the property 'MoonScanUrl'
        }
        /// <summary>
        /// Test the property 'Signature'
        /// </summary>
        [Test]
        public void SignatureTest()
        {
            // TODO unit test for the property 'Signature'
        }
        /// <summary>
        /// Test the property 'Transaction'
        /// </summary>
        [Test]
        public void TransactionTest()
        {
            // TODO unit test for the property 'Transaction'
        }
        /// <summary>
        /// Test the property 'UserOps'
        /// </summary>
        [Test]
        public void UserOpsTest()
        {
            // TODO unit test for the property 'UserOps'
        }
        /// <summary>
        /// Test the property 'UseropTransaction'
        /// </summary>
        [Test]
        public void UseropTransactionTest()
        {
            // TODO unit test for the property 'UseropTransaction'
        }
        /// <summary>
        /// Test the property 'Keys'
        /// </summary>
        [Test]
        public void KeysTest()
        {
            // TODO unit test for the property 'Keys'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Encoding'
        /// </summary>
        [Test]
        public void EncodingTest()
        {
            // TODO unit test for the property 'Encoding'
        }
        /// <summary>
        /// Test the property 'Header'
        /// </summary>
        [Test]
        public void HeaderTest()
        {
            // TODO unit test for the property 'Header'
        }
        /// <summary>
        /// Test the property 'Signtype'
        /// </summary>
        [Test]
        public void SigntypeTest()
        {
            // TODO unit test for the property 'Signtype'
        }
        /// <summary>
        /// Test the property 'Domain'
        /// </summary>
        [Test]
        public void DomainTest()
        {
            // TODO unit test for the property 'Domain'
        }
        /// <summary>
        /// Test the property 'CurrentAtokenBalance'
        /// </summary>
        [Test]
        public void CurrentAtokenBalanceTest()
        {
            // TODO unit test for the property 'CurrentAtokenBalance'
        }
        /// <summary>
        /// Test the property 'CurrentBorrowBalance'
        /// </summary>
        [Test]
        public void CurrentBorrowBalanceTest()
        {
            // TODO unit test for the property 'CurrentBorrowBalance'
        }
        /// <summary>
        /// Test the property 'PrincipalBorrowBalance'
        /// </summary>
        [Test]
        public void PrincipalBorrowBalanceTest()
        {
            // TODO unit test for the property 'PrincipalBorrowBalance'
        }
        /// <summary>
        /// Test the property 'BorrowRateMode'
        /// </summary>
        [Test]
        public void BorrowRateModeTest()
        {
            // TODO unit test for the property 'BorrowRateMode'
        }
        /// <summary>
        /// Test the property 'BorrowRate'
        /// </summary>
        [Test]
        public void BorrowRateTest()
        {
            // TODO unit test for the property 'BorrowRate'
        }
        /// <summary>
        /// Test the property 'LiquidityRate'
        /// </summary>
        [Test]
        public void LiquidityRateTest()
        {
            // TODO unit test for the property 'LiquidityRate'
        }
        /// <summary>
        /// Test the property 'OriginationFee'
        /// </summary>
        [Test]
        public void OriginationFeeTest()
        {
            // TODO unit test for the property 'OriginationFee'
        }
        /// <summary>
        /// Test the property 'VariableBorrowIndex'
        /// </summary>
        [Test]
        public void VariableBorrowIndexTest()
        {
            // TODO unit test for the property 'VariableBorrowIndex'
        }
        /// <summary>
        /// Test the property 'LastUpdateTimestamp'
        /// </summary>
        [Test]
        public void LastUpdateTimestampTest()
        {
            // TODO unit test for the property 'LastUpdateTimestamp'
        }
        /// <summary>
        /// Test the property 'UsageAsCollateralEnabled'
        /// </summary>
        [Test]
        public void UsageAsCollateralEnabledTest()
        {
            // TODO unit test for the property 'UsageAsCollateralEnabled'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'ChainId'
        /// </summary>
        [Test]
        public void ChainIdTest()
        {
            // TODO unit test for the property 'ChainId'
        }
        /// <summary>
        /// Test the property 'Gas'
        /// </summary>
        [Test]
        public void GasTest()
        {
            // TODO unit test for the property 'Gas'
        }
        /// <summary>
        /// Test the property 'GasPrice'
        /// </summary>
        [Test]
        public void GasPriceTest()
        {
            // TODO unit test for the property 'GasPrice'
        }
        /// <summary>
        /// Test the property 'GasTipCap'
        /// </summary>
        [Test]
        public void GasTipCapTest()
        {
            // TODO unit test for the property 'GasTipCap'
        }
        /// <summary>
        /// Test the property 'GasFeeCap'
        /// </summary>
        [Test]
        public void GasFeeCapTest()
        {
            // TODO unit test for the property 'GasFeeCap'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Test]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }
        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Test]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }
        /// <summary>
        /// Test the property 'BlobGas'
        /// </summary>
        [Test]
        public void BlobGasTest()
        {
            // TODO unit test for the property 'BlobGas'
        }
        /// <summary>
        /// Test the property 'BlobGasFeeCap'
        /// </summary>
        [Test]
        public void BlobGasFeeCapTest()
        {
            // TODO unit test for the property 'BlobGasFeeCap'
        }
        /// <summary>
        /// Test the property 'BlobHashes'
        /// </summary>
        [Test]
        public void BlobHashesTest()
        {
            // TODO unit test for the property 'BlobHashes'
        }
        /// <summary>
        /// Test the property 'V'
        /// </summary>
        [Test]
        public void VTest()
        {
            // TODO unit test for the property 'V'
        }
        /// <summary>
        /// Test the property 'R'
        /// </summary>
        [Test]
        public void RTest()
        {
            // TODO unit test for the property 'R'
        }
        /// <summary>
        /// Test the property 'S'
        /// </summary>
        [Test]
        public void STest()
        {
            // TODO unit test for the property 'S'
        }
        /// <summary>
        /// Test the property 'Symbol'
        /// </summary>
        [Test]
        public void SymbolTest()
        {
            // TODO unit test for the property 'Symbol'
        }
        /// <summary>
        /// Test the property 'Decimals'
        /// </summary>
        [Test]
        public void DecimalsTest()
        {
            // TODO unit test for the property 'Decimals'
        }
        /// <summary>
        /// Test the property 'TotalSupply'
        /// </summary>
        [Test]
        public void TotalSupplyTest()
        {
            // TODO unit test for the property 'TotalSupply'
        }
        /// <summary>
        /// Test the property 'ContractAddress'
        /// </summary>
        [Test]
        public void ContractAddressTest()
        {
            // TODO unit test for the property 'ContractAddress'
        }
        /// <summary>
        /// Test the property 'BalanceOf'
        /// </summary>
        [Test]
        public void BalanceOfTest()
        {
            // TODO unit test for the property 'BalanceOf'
        }
        /// <summary>
        /// Test the property 'Allowance'
        /// </summary>
        [Test]
        public void AllowanceTest()
        {
            // TODO unit test for the property 'Allowance'
        }
        /// <summary>
        /// Test the property 'BalanceOf'
        /// </summary>
        [Test]
        public void BalanceOfTest()
        {
            // TODO unit test for the property 'BalanceOf'
        }
        /// <summary>
        /// Test the property 'BalanceOfBatch'
        /// </summary>
        [Test]
        public void BalanceOfBatchTest()
        {
            // TODO unit test for the property 'BalanceOfBatch'
        }
        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Test]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'SignedTx'
        /// </summary>
        [Test]
        public void SignedTxTest()
        {
            // TODO unit test for the property 'SignedTx'
        }
        /// <summary>
        /// Test the property 'OwnerOf'
        /// </summary>
        [Test]
        public void OwnerOfTest()
        {
            // TODO unit test for the property 'OwnerOf'
        }
        /// <summary>
        /// Test the property 'TokenUri'
        /// </summary>
        [Test]
        public void TokenUriTest()
        {
            // TODO unit test for the property 'TokenUri'
        }
        /// <summary>
        /// Test the property 'IsApprovedForAll'
        /// </summary>
        [Test]
        public void IsApprovedForAllTest()
        {
            // TODO unit test for the property 'IsApprovedForAll'
        }
    }
}
