/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.usemoon.MoonSDK.Api;
using com.usemoon.MoonSDK.Model;
using com.usemoon.MoonSDK.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace com.usemoon.MoonSDK.Test.Model
{
    /// <summary>
    ///  Class for testing DeployInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeployInputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DeployInput
        //private DeployInput instance;

        public DeployInputTests()
        {
            // TODO uncomment below to create an instance of DeployInput
            //instance = new DeployInput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeployInput
        /// </summary>
        [Test]
        public void DeployInputInstanceTest()
        {
            // TODO uncomment below to test "IsType" DeployInput
            //Assert.IsType<DeployInput>(instance);
        }

        /// <summary>
        /// Test the property 'ChainId'
        /// </summary>
        [Test]
        public void ChainIdTest()
        {
            // TODO unit test for the property 'ChainId'
        }
        /// <summary>
        /// Test the property 'Abi'
        /// </summary>
        [Test]
        public void AbiTest()
        {
            // TODO unit test for the property 'Abi'
        }
        /// <summary>
        /// Test the property 'Bytecode'
        /// </summary>
        [Test]
        public void BytecodeTest()
        {
            // TODO unit test for the property 'Bytecode'
        }
        /// <summary>
        /// Test the property 'ConstructorArgs'
        /// </summary>
        [Test]
        public void ConstructorArgsTest()
        {
            // TODO unit test for the property 'ConstructorArgs'
        }
    }
}
