/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.usemoon.MoonSDK.Api;
using com.usemoon.MoonSDK.Model;
using com.usemoon.MoonSDK.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace com.usemoon.MoonSDK.Test.Model
{
    /// <summary>
    ///  Class for testing IERC20Approval
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IERC20ApprovalTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IERC20Approval
        //private IERC20Approval instance;

        public IERC20ApprovalTests()
        {
            // TODO uncomment below to create an instance of IERC20Approval
            //instance = new IERC20Approval();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IERC20Approval
        /// </summary>
        [Test]
        public void IERC20ApprovalInstanceTest()
        {
            // TODO uncomment below to test "IsType" IERC20Approval
            //Assert.IsType<IERC20Approval>(instance);
        }

        /// <summary>
        /// Test the property 'TransactionHash'
        /// </summary>
        [Test]
        public void TransactionHashTest()
        {
            // TODO unit test for the property 'TransactionHash'
        }
        /// <summary>
        /// Test the property 'Contract'
        /// </summary>
        [Test]
        public void ContractTest()
        {
            // TODO unit test for the property 'Contract'
        }
        /// <summary>
        /// Test the property 'LogIndex'
        /// </summary>
        [Test]
        public void LogIndexTest()
        {
            // TODO unit test for the property 'LogIndex'
        }
        /// <summary>
        /// Test the property 'Owner'
        /// </summary>
        [Test]
        public void OwnerTest()
        {
            // TODO unit test for the property 'Owner'
        }
        /// <summary>
        /// Test the property 'Spender'
        /// </summary>
        [Test]
        public void SpenderTest()
        {
            // TODO unit test for the property 'Spender'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'TokenDecimals'
        /// </summary>
        [Test]
        public void TokenDecimalsTest()
        {
            // TODO unit test for the property 'TokenDecimals'
        }
        /// <summary>
        /// Test the property 'TokenName'
        /// </summary>
        [Test]
        public void TokenNameTest()
        {
            // TODO unit test for the property 'TokenName'
        }
        /// <summary>
        /// Test the property 'TokenSymbol'
        /// </summary>
        [Test]
        public void TokenSymbolTest()
        {
            // TODO unit test for the property 'TokenSymbol'
        }
        /// <summary>
        /// Test the property 'ValueWithDecimals'
        /// </summary>
        [Test]
        public void ValueWithDecimalsTest()
        {
            // TODO unit test for the property 'ValueWithDecimals'
        }
        /// <summary>
        /// Test the property 'Triggers'
        /// </summary>
        [Test]
        public void TriggersTest()
        {
            // TODO unit test for the property 'Triggers'
        }
    }
}
