/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.usemoon.MoonSDK.Api;
using com.usemoon.MoonSDK.Model;
using com.usemoon.MoonSDK.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace com.usemoon.MoonSDK.Test.Model
{
    /// <summary>
    ///  Class for testing Transaction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransactionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Transaction
        //private Transaction instance;

        public TransactionTests()
        {
            // TODO uncomment below to create an instance of Transaction
            //instance = new Transaction();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Transaction
        /// </summary>
        [Test]
        public void TransactionInstanceTest()
        {
            // TODO uncomment below to test "IsType" Transaction
            //Assert.IsType<Transaction>(instance);
        }

        /// <summary>
        /// Test the property 'TransactionHash'
        /// </summary>
        [Test]
        public void TransactionHashTest()
        {
            // TODO unit test for the property 'TransactionHash'
        }
        /// <summary>
        /// Test the property 'SignedTransaction'
        /// </summary>
        [Test]
        public void SignedTransactionTest()
        {
            // TODO unit test for the property 'SignedTransaction'
        }
        /// <summary>
        /// Test the property 'RawTransaction'
        /// </summary>
        [Test]
        public void RawTransactionTest()
        {
            // TODO unit test for the property 'RawTransaction'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'Transactions'
        /// </summary>
        [Test]
        public void TransactionsTest()
        {
            // TODO unit test for the property 'Transactions'
        }
        /// <summary>
        /// Test the property 'MoonScanUrl'
        /// </summary>
        [Test]
        public void MoonScanUrlTest()
        {
            // TODO unit test for the property 'MoonScanUrl'
        }
        /// <summary>
        /// Test the property 'Signature'
        /// </summary>
        [Test]
        public void SignatureTest()
        {
            // TODO unit test for the property 'Signature'
        }
        /// <summary>
        /// Test the property 'VarTransaction'
        /// </summary>
        [Test]
        public void VarTransactionTest()
        {
            // TODO unit test for the property 'VarTransaction'
        }
        /// <summary>
        /// Test the property 'UserOps'
        /// </summary>
        [Test]
        public void UserOpsTest()
        {
            // TODO unit test for the property 'UserOps'
        }
        /// <summary>
        /// Test the property 'UseropTransaction'
        /// </summary>
        [Test]
        public void UseropTransactionTest()
        {
            // TODO unit test for the property 'UseropTransaction'
        }
    }
}
