/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.usemoon.MoonSDK.Api;
using com.usemoon.MoonSDK.Model;
using com.usemoon.MoonSDK.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace com.usemoon.MoonSDK.Test.Model
{
    /// <summary>
    ///  Class for testing TransactionResponseTx
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransactionResponseTxTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TransactionResponseTx
        //private TransactionResponseTx instance;

        public TransactionResponseTxTests()
        {
            // TODO uncomment below to create an instance of TransactionResponseTx
            //instance = new TransactionResponseTx();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TransactionResponseTx
        /// </summary>
        [Test]
        public void TransactionResponseTxInstanceTest()
        {
            // TODO uncomment below to test "IsType" TransactionResponseTx
            //Assert.IsType<TransactionResponseTx>(instance);
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'Nonce'
        /// </summary>
        [Test]
        public void NonceTest()
        {
            // TODO unit test for the property 'Nonce'
        }
        /// <summary>
        /// Test the property 'Gas'
        /// </summary>
        [Test]
        public void GasTest()
        {
            // TODO unit test for the property 'Gas'
        }
        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Test]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }
        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Test]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }
    }
}
