/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.usemoon.MoonSDK.Api;
using com.usemoon.MoonSDK.Model;
using com.usemoon.MoonSDK.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace com.usemoon.MoonSDK.Test.Model
{
    /// <summary>
    ///  Class for testing TransactionInputSupportedParamsTheme
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransactionInputSupportedParamsThemeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TransactionInputSupportedParamsTheme
        //private TransactionInputSupportedParamsTheme instance;

        public TransactionInputSupportedParamsThemeTests()
        {
            // TODO uncomment below to create an instance of TransactionInputSupportedParamsTheme
            //instance = new TransactionInputSupportedParamsTheme();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TransactionInputSupportedParamsTheme
        /// </summary>
        [Test]
        public void TransactionInputSupportedParamsThemeInstanceTest()
        {
            // TODO uncomment below to test "IsType" TransactionInputSupportedParamsTheme
            //Assert.IsType<TransactionInputSupportedParamsTheme>(instance);
        }

        /// <summary>
        /// Test the property 'BorderRadius'
        /// </summary>
        [Test]
        public void BorderRadiusTest()
        {
            // TODO unit test for the property 'BorderRadius'
        }
        /// <summary>
        /// Test the property 'CardColor'
        /// </summary>
        [Test]
        public void CardColorTest()
        {
            // TODO unit test for the property 'CardColor'
        }
        /// <summary>
        /// Test the property 'SecondaryTextColor'
        /// </summary>
        [Test]
        public void SecondaryTextColorTest()
        {
            // TODO unit test for the property 'SecondaryTextColor'
        }
        /// <summary>
        /// Test the property 'PrimaryTextColor'
        /// </summary>
        [Test]
        public void PrimaryTextColorTest()
        {
            // TODO unit test for the property 'PrimaryTextColor'
        }
        /// <summary>
        /// Test the property 'SecondaryColor'
        /// </summary>
        [Test]
        public void SecondaryColorTest()
        {
            // TODO unit test for the property 'SecondaryColor'
        }
        /// <summary>
        /// Test the property 'PrimaryColor'
        /// </summary>
        [Test]
        public void PrimaryColorTest()
        {
            // TODO unit test for the property 'PrimaryColor'
        }
        /// <summary>
        /// Test the property 'ThemeName'
        /// </summary>
        [Test]
        public void ThemeNameTest()
        {
            // TODO unit test for the property 'ThemeName'
        }
        /// <summary>
        /// Test the property 'IsDark'
        /// </summary>
        [Test]
        public void IsDarkTest()
        {
            // TODO unit test for the property 'IsDark'
        }
    }
}
