/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing DogeCoinApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class DogeCoinApiTests : IDisposable
    {
        private DogeCoinApi instance;

        public DogeCoinApiTests()
        {
            instance = new DogeCoinApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DogeCoinApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' DogeCoinApi
            //Assert.IsType<DogeCoinApi>(instance);
        }

        /// <summary>
        /// Test CreateDogeCoinAccount
        /// </summary>
        [Fact]
        public void CreateDogeCoinAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string authorization = null;
            //DogeCoinInput dogeCoinInput = null;
            //var response = instance.CreateDogeCoinAccount(authorization, dogeCoinInput);
            //Assert.IsType<AccountControllerResponse>(response);
        }

        /// <summary>
        /// Test GetDogeCoinAccount
        /// </summary>
        [Fact]
        public void GetDogeCoinAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string authorization = null;
            //string accountName = null;
            //var response = instance.GetDogeCoinAccount(authorization, accountName);
            //Assert.IsType<AccountControllerResponse>(response);
        }

        /// <summary>
        /// Test ListDogeCoinAccounts
        /// </summary>
        [Fact]
        public void ListDogeCoinAccountsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string authorization = null;
            //var response = instance.ListDogeCoinAccounts(authorization);
            //Assert.IsType<AccountControllerResponse>(response);
        }

        /// <summary>
        /// Test SignDogeCoinTransaction
        /// </summary>
        [Fact]
        public void SignDogeCoinTransactionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string authorization = null;
            //string accountName = null;
            //DogeCoinTransactionInput dogeCoinTransactionInput = null;
            //var response = instance.SignDogeCoinTransaction(authorization, accountName, dogeCoinTransactionInput);
            //Assert.IsType<AccountControllerResponse>(response);
        }
    }
}
