/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = com.usemoon.MoonSDK.Client.OpenAPIDateConverter;

namespace com.usemoon.MoonSDK.Model
{
    /// <summary>
    /// DeployInput
    /// </summary>
    [DataContract(Name = "DeployInput")]
    public partial class DeployInput
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DeployInput" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DeployInput() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DeployInput" /> class.
        /// </summary>
        /// <param name="chainId">chainId.</param>
        /// <param name="abi">abi (required).</param>
        /// <param name="bytecode">bytecode (required).</param>
        /// <param name="constructorArgs">constructorArgs.</param>
        public DeployInput(string chainId = default(string), string abi = default(string), string bytecode = default(string), string constructorArgs = default(string))
        {
            // to ensure "abi" is required (not null)
            if (abi == null)
            {
                throw new ArgumentNullException("abi is a required property for DeployInput and cannot be null");
            }
            this.Abi = abi;
            // to ensure "bytecode" is required (not null)
            if (bytecode == null)
            {
                throw new ArgumentNullException("bytecode is a required property for DeployInput and cannot be null");
            }
            this.Bytecode = bytecode;
            this.ChainId = chainId;
            this.ConstructorArgs = constructorArgs;
        }

        /// <summary>
        /// Gets or Sets ChainId
        /// </summary>
        [DataMember(Name = "chain_id", EmitDefaultValue = false)]
        public string ChainId { get; set; }

        /// <summary>
        /// Gets or Sets Abi
        /// </summary>
        [DataMember(Name = "abi", IsRequired = true, EmitDefaultValue = true)]
        public string Abi { get; set; }

        /// <summary>
        /// Gets or Sets Bytecode
        /// </summary>
        [DataMember(Name = "bytecode", IsRequired = true, EmitDefaultValue = true)]
        public string Bytecode { get; set; }

        /// <summary>
        /// Gets or Sets ConstructorArgs
        /// </summary>
        [DataMember(Name = "constructor_args", EmitDefaultValue = false)]
        public string ConstructorArgs { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DeployInput {\n");
            sb.Append("  ChainId: ").Append(ChainId).Append("\n");
            sb.Append("  Abi: ").Append(Abi).Append("\n");
            sb.Append("  Bytecode: ").Append(Bytecode).Append("\n");
            sb.Append("  ConstructorArgs: ").Append(ConstructorArgs).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
