/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using NUnit.Framework;

using com.usemoon.MoonSDK.Client;
using com.usemoon.MoonSDK.Api;
// uncomment below to import models
//using com.usemoon.MoonSDK.Model;

namespace com.usemoon.MoonSDK.Test.Api
{
    /// <summary>
    ///  Class for testing ConveyorFinanceApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ConveyorFinanceApiTests : IDisposable
    {
        private ConveyorFinanceApi instance;

        public ConveyorFinanceApiTests()
        {
            instance = new ConveyorFinanceApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConveyorFinanceApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ConveyorFinanceApi
            //Assert.IsType<ConveyorFinanceApi>(instance);
        }

        /// <summary>
        /// Test Swap
        /// </summary>
        [Test]
        public void SwapTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string authorization = null;
            //string name = null;
            //TokenSwapParams tokenSwapParams = null;
            //var response = instance.Swap(authorization, name, tokenSwapParams);
            //Assert.IsType<ConveyorFinanceControllerResponse>(response);
        }
    }
}
