/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing AccountResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AccountResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AccountResponse
        //private AccountResponse instance;

        public AccountResponseTests()
        {
            // TODO uncomment below to create an instance of AccountResponse
            //instance = new AccountResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AccountResponse
        /// </summary>
        [Fact]
        public void AccountResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" AccountResponse
            //Assert.IsType<AccountResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Keys'
        /// </summary>
        [Fact]
        public void KeysTest()
        {
            // TODO unit test for the property 'Keys'
        }

        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
    }
}
