/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing SolanaTransactionOutput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SolanaTransactionOutputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SolanaTransactionOutput
        //private SolanaTransactionOutput instance;

        public SolanaTransactionOutputTests()
        {
            // TODO uncomment below to create an instance of SolanaTransactionOutput
            //instance = new SolanaTransactionOutput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SolanaTransactionOutput
        /// </summary>
        [Fact]
        public void SolanaTransactionOutputInstanceTest()
        {
            // TODO uncomment below to test "IsType" SolanaTransactionOutput
            //Assert.IsType<SolanaTransactionOutput>(instance);
        }

        /// <summary>
        /// Test the property 'SignedTx'
        /// </summary>
        [Fact]
        public void SignedTxTest()
        {
            // TODO unit test for the property 'SignedTx'
        }

        /// <summary>
        /// Test the property 'TransactionHash'
        /// </summary>
        [Fact]
        public void TransactionHashTest()
        {
            // TODO unit test for the property 'TransactionHash'
        }
    }
}
