/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing TransactionInputSupportedParamsPartnerData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransactionInputSupportedParamsPartnerDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TransactionInputSupportedParamsPartnerData
        //private TransactionInputSupportedParamsPartnerData instance;

        public TransactionInputSupportedParamsPartnerDataTests()
        {
            // TODO uncomment below to create an instance of TransactionInputSupportedParamsPartnerData
            //instance = new TransactionInputSupportedParamsPartnerData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TransactionInputSupportedParamsPartnerData
        /// </summary>
        [Fact]
        public void TransactionInputSupportedParamsPartnerDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" TransactionInputSupportedParamsPartnerData
            //Assert.IsType<TransactionInputSupportedParamsPartnerData>(instance);
        }

        /// <summary>
        /// Test the property 'RedirectUrl'
        /// </summary>
        [Fact]
        public void RedirectUrlTest()
        {
            // TODO unit test for the property 'RedirectUrl'
        }
    }
}
