/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Tx
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TxTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Tx
        //private Tx instance;

        public TxTests()
        {
            // TODO uncomment below to create an instance of Tx
            //instance = new Tx();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Tx
        /// </summary>
        [Fact]
        public void TxInstanceTest()
        {
            // TODO uncomment below to test "IsType" Tx
            //Assert.IsType<Tx>(instance);
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'ChainId'
        /// </summary>
        [Fact]
        public void ChainIdTest()
        {
            // TODO unit test for the property 'ChainId'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'Gas'
        /// </summary>
        [Fact]
        public void GasTest()
        {
            // TODO unit test for the property 'Gas'
        }

        /// <summary>
        /// Test the property 'GasPrice'
        /// </summary>
        [Fact]
        public void GasPriceTest()
        {
            // TODO unit test for the property 'GasPrice'
        }

        /// <summary>
        /// Test the property 'GasTipCap'
        /// </summary>
        [Fact]
        public void GasTipCapTest()
        {
            // TODO unit test for the property 'GasTipCap'
        }

        /// <summary>
        /// Test the property 'GasFeeCap'
        /// </summary>
        [Fact]
        public void GasFeeCapTest()
        {
            // TODO unit test for the property 'GasFeeCap'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

        /// <summary>
        /// Test the property 'Nonce'
        /// </summary>
        [Fact]
        public void NonceTest()
        {
            // TODO unit test for the property 'Nonce'
        }

        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Fact]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }

        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Fact]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }

        /// <summary>
        /// Test the property 'BlobGas'
        /// </summary>
        [Fact]
        public void BlobGasTest()
        {
            // TODO unit test for the property 'BlobGas'
        }

        /// <summary>
        /// Test the property 'BlobGasFeeCap'
        /// </summary>
        [Fact]
        public void BlobGasFeeCapTest()
        {
            // TODO unit test for the property 'BlobGasFeeCap'
        }

        /// <summary>
        /// Test the property 'BlobHashes'
        /// </summary>
        [Fact]
        public void BlobHashesTest()
        {
            // TODO unit test for the property 'BlobHashes'
        }

        /// <summary>
        /// Test the property 'V'
        /// </summary>
        [Fact]
        public void VTest()
        {
            // TODO unit test for the property 'V'
        }

        /// <summary>
        /// Test the property 'R'
        /// </summary>
        [Fact]
        public void RTest()
        {
            // TODO unit test for the property 'R'
        }

        /// <summary>
        /// Test the property 'S'
        /// </summary>
        [Fact]
        public void STest()
        {
            // TODO unit test for the property 'S'
        }
    }
}
